plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'test/**/*'

# スタイル設定
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# レイアウト設定
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'

# メトリクス設定
Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'db/seeds.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/**/*'

# Rails設定
Rails/I18nLocaleTexts:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/Exit:
  Exclude:
    - 'spec/**/*'

# RSpec設定
RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 8

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/ContextWording:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/LetSetup:
  Enabled: false
